# Full test suite for standalone Testkube agent.
#
# Note: the `execute: workflows:` orchestration pattern requires Testkube Pro/Cloud.
# In standalone mode all steps must be inlined into a single TestWorkflow.
# The individual task-manager-unit/integration/e2e workflows still exist for
# running tests in isolation; this workflow runs all three in sequence.
apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: task-manager-suite
  namespace: testkube
  labels:
    app: task-manager
spec:
  content:
    git:
      uri: https://github.com/jonmell78/testkube.git
      revision: main

  # App sidecar used by the E2E steps
  services:
    app:
      image: node:22-alpine
      content:
        git:
          uri: https://github.com/jonmell78/testkube.git
          revision: main
      readinessProbe:
        httpGet:
          path: /health
          port: 3000
        periodSeconds: 2
        failureThreshold: 15
      container:
        workingDir: /data/repo
        env:
          - name: PORT
            value: "3000"
          - name: NODE_ENV
            value: test
          - name: DB_PATH
            value: /tmp/test-e2e.db
      shell: npm ci && node src/server.js

  container:
    workingDir: /data/repo

  steps:
    # ── Unit tests ──────────────────────────────────────────────
    - name: Install dependencies (unit)
      container:
        image: node:22-alpine
      shell: npm ci

    - name: Run unit tests
      container:
        image: node:22-alpine
      shell: npm run test:unit -- --ci --coverage
      env:
        - name: NODE_ENV
          value: test

    - name: Save unit coverage
      condition: always
      container:
        image: node:22-alpine
      artifacts:
        paths:
          - coverage/**/*

    # ── Integration tests ────────────────────────────────────────
    - name: Run integration tests
      container:
        image: node:22-alpine
      shell: npm run test:integration -- --ci
      env:
        - name: NODE_ENV
          value: test

    # ── E2E tests ─────────────────────────────────────────────────
    - name: Install Playwright browsers
      condition: always
      container:
        image: mcr.microsoft.com/playwright:v1.42.1-jammy
      shell: npm ci && npx playwright install --with-deps chromium

    - name: Run E2E tests
      condition: always
      container:
        image: mcr.microsoft.com/playwright:v1.42.1-jammy
      shell: npm run test:e2e
      env:
        - name: NODE_ENV
          value: test
        - name: CI
          value: "true"
        - name: PLAYWRIGHT_BASE_URL
          value: "http://{{services.app.0.ip}}:3000"

    - name: Save Playwright artifacts
      condition: always
      container:
        image: mcr.microsoft.com/playwright:v1.42.1-jammy
      artifacts:
        paths:
          - playwright-report/**/*
          - test-results/**/*
