apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: task-manager-e2e
  namespace: testkube
  labels:
    app: task-manager
    type: e2e
spec:
  content:
    git:
      uri: https://github.com/jonmell78/testkube.git
      revision: main
  container:
    image: mcr.microsoft.com/playwright:v1.42.1-jammy
    workingDir: /data/repo
  steps:
    - name: Install dependencies
      shell: npm ci

    - name: Install Playwright browsers
      shell: npx playwright install --with-deps chromium

    - name: Run E2E tests
      shell: npm run test:e2e
      env:
        - name: NODE_ENV
          value: test
        - name: CI
          value: "true"

    - name: Save Playwright artifacts
      condition: always
      artifacts:
        paths:
          - playwright-report/**/*
          - test-results/**/*
