apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: task-manager-integration
  namespace: testkube
  labels:
    app: task-manager
    type: integration
spec:
  content:
    git:
      uri: https://github.com/jonmell78/testkube.git
      revision: main
  container:
    image: node:22-alpine
    workingDir: /data/repo
  steps:
    - name: Install dependencies
      shell: npm ci

    - name: Run integration tests
      shell: |
        export NODE_ENV=test
        npm run test:integration -- --ci
