apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: task-manager-e2e
  namespace: testkube
  labels:
    app: task-manager
    type: e2e
spec:
  content:
    git:
      uri: https://github.com/jonmell78/testkube.git
      revision: main
  container:
    image: mcr.microsoft.com/playwright:v1.58.2-jammy
    workingDir: /data/repo
  steps:
    - name: Install dependencies
      shell: npm ci

    - name: Install Playwright browsers
      shell: npx playwright install --with-deps chromium

    - name: Run E2E tests
      shell: |
        export DB_PATH=/tmp/test-e2e.db
        export PORT=3000
        export NODE_ENV=test
        export CI=true
        export PLAYWRIGHT_BASE_URL=http://localhost:3000
        nohup node src/server.js > /tmp/app.log 2>&1 &
        for i in $(seq 1 60); do
          curl -sf http://localhost:3000/health > /dev/null 2>&1 && { echo "App ready after ${i}s"; break; }
          [ $i -eq 60 ] && { echo "App failed to start:"; cat /tmp/app.log; exit 1; }
          sleep 1
        done
        npm run test:e2e

    - name: Save Playwright artifacts
      condition: always
      artifacts:
        paths:
          - playwright-report/**/*
          - test-results/**/*
