apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: task-manager-e2e
  namespace: testkube
  labels:
    app: task-manager
    type: e2e
spec:
  content:
    git:
      uri: https://github.com/jonmell78/testkube.git
      revision: main
  # Run the app as a sidecar so Playwright tests hit a real server
  services:
    app:
      image: node:22-alpine
      content:
        git:
          uri: https://github.com/jonmell78/testkube.git
          revision: main
      readinessProbe:
        httpGet:
          path: /health
          port: 3000
        periodSeconds: 2
        failureThreshold: 15
      container:
        workingDir: /data/repo
        env:
          - name: PORT
            value: "3000"
          - name: NODE_ENV
            value: test
          - name: DB_PATH
            value: /tmp/test-e2e.db
      shell: npm ci && node src/server.js
  container:
    image: mcr.microsoft.com/playwright:v1.42.1-jammy
    workingDir: /data/repo
  steps:
    - name: Install dependencies
      shell: npm ci

    - name: Install Playwright browsers
      shell: npx playwright install --with-deps chromium

    - name: Run E2E tests
      shell: npm run test:e2e
      env:
        - name: NODE_ENV
          value: test
        - name: CI
          value: "true"
        - name: PLAYWRIGHT_BASE_URL
          value: "http://{{services.app.0.ip}}:3000"

    - name: Save Playwright artifacts
      condition: always
      artifacts:
        paths:
          - playwright-report/**/*
          - test-results/**/*
