apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: task-manager-suite
  namespace: testkube
  labels:
    app: task-manager
spec:
  steps:
    # Unit tests — abort if they fail
    - name: Unit tests
      execute:
        workflows:
          - name: task-manager-unit

    # Integration tests — abort if they fail
    - name: Integration tests
      execute:
        workflows:
          - name: task-manager-integration

    # E2E tests — run regardless of above (collect report either way)
    - name: E2E tests
      condition: always
      execute:
        workflows:
          - name: task-manager-e2e
