apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: task-manager-suite
  namespace: testkube
  labels:
    app: task-manager
spec:
  content:
    git:
      uri: https://github.com/jonmell78/testkube.git
      revision: main
  container:
    workingDir: /data/repo
  steps:
    # ── Unit tests ──────────────────────────────────────────────
    - name: Install dependencies
      container:
        image: node:22-alpine
      shell: npm ci

    - name: Run unit tests
      container:
        image: node:22-alpine
      shell: |
        export NODE_ENV=test
        npm run test:unit -- --ci --coverage

    - name: Save unit coverage
      condition: always
      container:
        image: node:22-alpine
      artifacts:
        paths:
          - coverage/**/*

    # ── Integration tests ────────────────────────────────────────
    - name: Run integration tests
      container:
        image: node:22-alpine
      shell: |
        export NODE_ENV=test
        npm run test:integration -- --ci

    # ── E2E tests ─────────────────────────────────────────────────
    - name: Install Playwright dependencies and browsers
      condition: always
      container:
        image: mcr.microsoft.com/playwright:v1.58.2-jammy
      shell: npm ci && npx playwright install --with-deps chromium

    - name: Run E2E tests
      condition: always
      container:
        image: mcr.microsoft.com/playwright:v1.58.2-jammy
      shell: |
        export DB_PATH=/tmp/test-e2e.db
        export PORT=3001
        export NODE_ENV=test
        export CI=true
        nohup node src/server.js > /tmp/app.log 2>&1 &
        for i in $(seq 1 60); do
          curl -sf http://localhost:3001/health > /dev/null 2>&1 && { echo "App ready after ${i}s"; break; }
          [ $i -eq 60 ] && { echo "App failed to start:"; cat /tmp/app.log; exit 1; }
          sleep 1
        done
        npm run test:e2e

    - name: Save Playwright artifacts
      condition: always
      container:
        image: mcr.microsoft.com/playwright:v1.58.2-jammy
      artifacts:
        paths:
          - playwright-report/**/*
          - test-results/**/*
