apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: task-manager-unit
  namespace: testkube
  labels:
    app: task-manager
    type: unit
spec:
  content:
    git:
      uri: https://github.com/jonmell78/testkube.git
      revision: main
  container:
    image: node:22-alpine
    workingDir: /data/repo
  steps:
    - name: Install dependencies
      shell: npm ci

    - name: Run unit tests
      shell: |
        export NODE_ENV=test
        npm run test:unit -- --ci --coverage

    - name: Save coverage artifacts
      condition: always
      artifacts:
        paths:
          - coverage/**/*
