apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: task-manager-e2e
  namespace: testkube
  labels:
    app: task-manager
    type: e2e
spec:
  content:
    git:
      uri: https://github.com/jonmell78/testkube.git
      revision: main
  container:
    image: mcr.microsoft.com/playwright:v1.42.1-jammy
    workingDir: /data/repo
  steps:
    - name: Install dependencies
      shell: npm ci

    - name: Install Playwright browsers
      shell: npx playwright install --with-deps chromium

    - name: Run E2E tests
      shell: |
        # Start app server in background
        DB_PATH=/tmp/test-e2e.db PORT=3000 NODE_ENV=test nohup node src/server.js > /tmp/app.log 2>&1 &
        APP_PID=$!
        # Wait up to 60s for the app to become ready
        for i in $(seq 1 60); do
          curl -sf http://localhost:3000/health > /dev/null 2>&1 && { echo "App ready after ${i}s"; break; }
          [ $i -eq 60 ] && { echo "App failed to start. Logs:"; cat /tmp/app.log; kill $APP_PID 2>/dev/null; exit 1; }
          sleep 1
        done
        NODE_ENV=test CI=true PLAYWRIGHT_BASE_URL=http://localhost:3000 npm run test:e2e
      env:
        - name: NODE_ENV
          value: test
        - name: CI
          value: "true"
        - name: PLAYWRIGHT_BASE_URL
          value: "http://localhost:3000"

    - name: Save Playwright artifacts
      condition: always
      artifacts:
        paths:
          - playwright-report/**/*
          - test-results/**/*
