# Full test suite for standalone Testkube agent.
#
# Note: the `execute: workflows:` orchestration pattern requires Testkube Pro/Cloud.
# In standalone mode all steps must be inlined into a single TestWorkflow.
# The individual task-manager-unit/integration/e2e workflows still exist for
# running tests in isolation; this workflow runs all three in sequence.
#
# E2E: the app server is started as a background process within the Run E2E tests
# step (services: sidecars are not available in standalone mode).
apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: task-manager-suite
  namespace: testkube
  labels:
    app: task-manager
spec:
  content:
    git:
      uri: https://github.com/jonmell78/testkube.git
      revision: main

  container:
    workingDir: /data/repo

  steps:
    # ── Unit tests ──────────────────────────────────────────────
    - name: Install dependencies (unit)
      container:
        image: node:22-alpine
      shell: npm ci

    - name: Run unit tests
      container:
        image: node:22-alpine
      shell: npm run test:unit -- --ci --coverage
      env:
        - name: NODE_ENV
          value: test

    - name: Save unit coverage
      condition: always
      container:
        image: node:22-alpine
      artifacts:
        paths:
          - coverage/**/*

    # ── Integration tests ────────────────────────────────────────
    - name: Run integration tests
      container:
        image: node:22-alpine
      shell: npm run test:integration -- --ci
      env:
        - name: NODE_ENV
          value: test

    # ── E2E tests ─────────────────────────────────────────────────
    - name: Install Playwright browsers
      condition: always
      container:
        image: mcr.microsoft.com/playwright:v1.58.2-jammy
      shell: npm ci && npx playwright install --with-deps chromium

    - name: Run E2E tests
      condition: always
      container:
        image: mcr.microsoft.com/playwright:v1.58.2-jammy
      shell: |
        export DB_PATH=/tmp/test-e2e.db
        export PORT=3000
        export NODE_ENV=test
        export CI=true
        export PLAYWRIGHT_BASE_URL=http://localhost:3000
        # Start app server in background
        nohup node src/server.js > /tmp/app.log 2>&1 &
        APP_PID=$!
        # Wait up to 60s for the app to become ready
        for i in $(seq 1 60); do
          curl -sf http://localhost:3000/health > /dev/null 2>&1 && { echo "App ready after ${i}s"; break; }
          [ $i -eq 60 ] && { echo "App failed to start. Logs:"; cat /tmp/app.log; kill $APP_PID 2>/dev/null; exit 1; }
          sleep 1
        done
        npm run test:e2e

    - name: Save Playwright artifacts
      condition: always
      container:
        image: mcr.microsoft.com/playwright:v1.58.2-jammy
      artifacts:
        paths:
          - playwright-report/**/*
          - test-results/**/*
