apiVersion: tests.testkube.io/v3
kind: TestSuite
metadata:
  name: task-manager-suite
  namespace: testkube
  labels:
    app: task-manager
spec:
  description: "Full test suite for Task Manager — unit, integration, and E2E"
  steps:
    - stopOnFailure: true
      execute:
        - test: task-manager-unit
    - stopOnFailure: true
      execute:
        - test: task-manager-integration
    - stopOnFailure: false
      execute:
        - test: task-manager-e2e
